Models/Loan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace Uppgift3.Models
{
    public class Loan
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // Foreign key 
        [Display(Name = "Låntagare")]
        public int BorrowerID { get; set; }

        [ForeignKey("BorrowerID")]
        [Display(Name = "Låntagare")]
        public virtual Borrower Borrower { get; set; }

        // Foreign key 
        [Display(Name = "CD")]
        public int CD_ID { get; set; }

        [ForeignKey("CD_ID")]
        public virtual CD CD { get; set; }

        [Required(ErrorMessage = "Lånedatum ska anges")]
        [ReadOnly(true)]
        [Display(Name = "Lånedatum")]
        public string LoanDate { get; set; } = DateTime.Now.ToShortDateString();

        [Required(ErrorMessage = "Förfallodatum ska anges")]
        [ReadOnly(true)]
        [Display(Name = "Förfallodatum")]
        public string BackDate { set; get; } = DateTime.Now.AddDays(30).ToShortDateString();

        [NotMapped]
        public List<SelectListItem> CDList { get; set; }
    }
}

Controllers/BorrowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Uppgift3.Models;

namespace Uppgift3.Controllers
{
    public class BorrowerController : Controller
    {
        private readonly DatabaseContext _context;

        public BorrowerController(DatabaseContext context)
        {
            _context = context;
            _context.Database.EnsureCreated();
        }

        // GET: Borrower
        public async Task<IActionResult> Index()
        {
            return View(await _context.Borrower.ToListAsync());
        }

        // GET: Borrower/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrower = await _context.Borrower
                .FirstOrDefaultAsync(m => m.ID == id);
            if (borrower == null)
            {
                return NotFound();
            }

            return View(borrower);
        }

        // GET: Borrower/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Borrower/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,SocialNumber,Address,Email")] Borrower borrower)
        {
            if (ModelState.IsValid)
            {
                _context.Add(borrower);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(borrower);
        }

        // GET: Borrower/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrower = await _context.Borrower.FindAsync(id);
            if (borrower == null)
            {
                return NotFound();
            }
            return View(borrower);
        }

        // POST: Borrower/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,SocialNumber,Address,Email")] Borrower borrower)
        {
            if (id != borrower.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(borrower);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BorrowerExists(borrower.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(borrower);
        }

        // GET: Borrower/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrower = await _context.Borrower
                .FirstOrDefaultAsync(m => m.ID == id);
            if (borrower == null)
            {
                return NotFound();
            }

            return View(borrower);
        }

        // POST: Borrower/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var borrower = await _context.Borrower.FindAsync(id);
            _context.Borrower.Remove(borrower);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BorrowerExists(int id)
        {
            return _context.Borrower.Any(e => e.ID == id);
        }
    }
}

Controllers/CDsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Uppgift3.Models;

namespace Uppgift3.Controllers
{
    public class CDsController : Controller
    {
        private readonly DatabaseContext _context;

        public CDsController(DatabaseContext context)
        {
            _context = context;
            _context.Database.EnsureCreated();
        }

        public IActionResult Search()
        {
            return View();
        }

        [HttpGet]
        [Route("CDS/SearchCDByArtist/{name}")]
        public IActionResult SearchCDByArtist(string name)
        {
            List<CD> templist = new List<CD>();
            List<CD> sendlist = new List<CD>();
            if (!string.IsNullOrEmpty(name) && !string.IsNullOrWhiteSpace(name))
            {
                /* Splittrar med tomma mellanrum;  */
                string[] keywords = name.Split(null);
                foreach (string wor in keywords)
                {
                    templist = _context.CD.Include(c => c.Artist).Where(cd => cd.Artist.Name.ToLower().Contains(wor.ToLower())).ToList();
                    if (templist.Count > 0)
                    {
                        foreach (CD ny in templist)
                        {
                            sendlist.Add(ny);
                        }
                    }
                }
                if (sendlist.Count > 0)
                {
                    /*  Går IGENOM SAMTLIGA RESULTAT och väljer DISTINKTA ID-NUMMER,
                    *  så att SAMMA ID-NUMMER INTE FÖREKOMMER FLERA GÅNGER; */
                    IEnumerable<CD> filteredList = sendlist.GroupBy(ku => ku.ID).Select(group => group.First());
                    /*  KONVERTERAR IEnumerable till LIST;   */
                    List<CD> nylista = new List<CD>(filteredList);
                    nylista.Sort((id1, id2) => id1.ID.CompareTo(id2.ID));
                    return Json(nylista);
                }
                else
                    return Json("Finns EJ");
            }
            return Json("Finns EJ");
        }

        [HttpGet]
        [Route("CDS/SearchCDByTitle/{title}")]
        public IActionResult SearchCDByTitle(string title)
        {
            List<CD> templist = new List<CD>();
            List<CD> sendlist = new List<CD>();
            if (!string.IsNullOrEmpty(title) && !string.IsNullOrWhiteSpace(title))
            {
                /* Splittrar med tomma mellanrum;  */
                string[] keywords = title.Split(null);
                foreach (string wor in keywords)
                {
                    templist = _context.CD.Include(c => c.Artist).Where(cd => cd.Title.ToLower().Contains(wor.ToLower())).ToList();
                    if (templist.Count > 0)
                    {
                        foreach (CD ny in templist)
                        {
                            sendlist.Add(ny);
                        }
                    }
                }
                if (sendlist.Count > 0)
                {
                    /*  Går IGENOM SAMTLIGA RESULTAT och väljer DISTINKTA ID-NUMMER,
                    *  så att SAMMA ID-NUMMER INTE FÖREKOMMER FLERA GÅNGER; */
                    IEnumerable<CD> filteredList = sendlist.GroupBy(ku => ku.ID).Select(group => group.First());
                    /*  KONVERTERAR IEnumerable till LIST;   */
                    List<CD> nylista = new List<CD>(filteredList);
                    nylista.Sort((id1, id2) => id1.ID.CompareTo(id2.ID));
                    return Json(nylista);
                }
                else
                    return Json("Finns EJ");
            }
            return Json("Finns EJ");
        }

    // GET: CDs
    public async Task<IActionResult> Index()
    {
        var databaseContext = _context.CD.Include(c => c.Artist);
        return View(await databaseContext.ToListAsync());
    }

    // GET: CDs/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cD = await _context.CD
            .Include(c => c.Artist)
            .FirstOrDefaultAsync(m => m.ID == id);
        if (cD == null)
        {
            return NotFound();
        }

        return View(cD);
    }

    // GET: CDs/Create
    public IActionResult Create()
    {
        if (_context.Artist != null && _context.Artist.Count() > 0)
            ViewData["ArtistID"] = new SelectList(_context.Artist, "ID", "Name");
        else
            ViewBag.Message = "Inga artister inlagda";
        return View();
    }

    // POST: CDs/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("ID,Title,ArtistID,Category,Year")] CD cD)
    {
        if (ModelState.IsValid)
        {
            _context.Add(cD);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name", cD.ArtistID);
        return View(cD);
    }

    // GET: CDs/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cD = await _context.CD.FindAsync(id);
        if (cD == null)
        {
            return NotFound();
        }
        ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name", cD.ArtistID);
        return View(cD);
    }

    // POST: CDs/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("ID,Title,ArtistID,Category,Year")] CD cD)
    {
        if (id != cD.ID)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(cD);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CDExists(cD.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["ArtistID"] = new SelectList(_context.Set<Artist>(), "ID", "Name", cD.ArtistID);
        return View(cD);
    }

    // GET: CDs/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cD = await _context.CD
            .Include(c => c.Artist)
            .FirstOrDefaultAsync(m => m.ID == id);
        if (cD == null)
        {
            return NotFound();
        }

        return View(cD);
    }

    // POST: CDs/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var cD = await _context.CD.FindAsync(id);
        _context.CD.Remove(cD);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool CDExists(int id)
    {
        return _context.CD.Any(e => e.ID == id);
    }
}
}

Views/Loan/Create.cshtml
@model Uppgift3.Models.Loan

@{
    ViewData["Title"] = "Create";
}

<h1>Låna CD-skiva under 30 dagar</h1>
<br />
<h4>Innan Du lånar ut CD-skivor, lägg in minst en låntagare samt önskade CD-skivor i databasen</h4>
<br />
<p class="blockquote">Lägg in minst en låntagare i databasen</p>
<p class="bg-light blockquote"><a href="@Url.Action("Create", "Borrower")" target="_blank"><b>Lägg in låntagare</b></a></p>
<br />
<p class="blockquote">För att lägga in en CD-skiva i databasen, måste Du först spara CD-skivans artist i databasen</p>
<p class="bg-light blockquote"><a href="@Url.Action("Create", "CDs")" target="_blank"><b>Lägg in en CD-skiva</b></a></p>
<p><hr /></p>
<h4>Fyll i lånet</h4>
<br/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BorrowerID" class="control-label"></label>
                <label class="control-label text-danger"><b>@ViewBag.Message1</b></label>
                <select asp-for="BorrowerID" class="form-control" asp-items="ViewBag.BorrowerID"></select>
            </div>
            <div class="form-group">
                <label asp-for="CD_ID" class="control-label"></label>
                <label class="control-label text-danger"><b>@ViewBag.Message2</b></label>
                @if (Model != null)
                {
                    <select asp-for="CD_ID" class="form-control" asp-items="Model.CDList"></select>
                }
            </div>
            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input asp-for="LoanDate" class="form-control" readonly="readonly" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackDate" class="control-label"></label>
                <input asp-for="BackDate" class="form-control" readonly="readonly" />
                <span asp-validation-for="BackDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Loan/Delete.cshtml
@model Uppgift3.Models.Loan

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Borrower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Borrower.Address)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CD.Category)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BackDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BackDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Loan/Details.cshtml
@model Uppgift3.Models.Loan

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Borrower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Borrower.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CD.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BackDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BackDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Loan/Edit.cshtml
@model Uppgift3.Models.Loan

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="BorrowerID" class="control-label"></label>
                <select asp-for="BorrowerID" class="form-control" asp-items="ViewBag.BorrowerID"></select>
                <span asp-validation-for="BorrowerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CD_ID" class="control-label"></label>
                <select asp-for="CD_ID" class="form-control" asp-items="ViewBag.CD_ID"></select>
                <span asp-validation-for="CD_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackDate" class="control-label"></label>
                <input asp-for="BackDate" class="form-control" />
                <span asp-validation-for="BackDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Loan/Index.cshtml
@model IEnumerable<Uppgift3.Models.Loan>

@{
    ViewData["Title"] = "Index";
}

<h1>Alla lån</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Borrower)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CD)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LoanDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BackDate)
            </th>
            <th>Åtgärder</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Borrower.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CD.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoanDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BackDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>